require 'cloudinary'
require 'cloudinary/uploader'
require 'cloudinary/utils'

# puts ENV["CLOUDINARY_URL"]

# # Cloudinary.config.url = ENV["CLOUDINARY_URL"]

# p Cloudinary.config

uploads = {}
eager_options = {
    :width => 200, :height => 150, :crop => "scale", :format => "jpg"
  }
# public_id for the uploaded image is generated by Cloudinary's service.
uploads[:test] = Cloudinary::Uploader.upload "/Users/peterhristakos/Downloads/images/no-image.png",
    :tags => "basic_sample",
    :public_id => "cover"
    
  uploads.each_value.with_index do |upload, index|
    puts "> Upload \##{index+1}:"
    puts "  Public ID: #{upload['public_id']}"
    puts "  URL: #{upload['url']}"

  end

  p uploads[:test]